# docker-compose things that are common for all
version: '3.1'

services:
  general-api:
    container_name: general-api
    image: autopacker/general-api

  general-db:
    image: mysql:8.0
    container_name: general-db