# docker-compose for local development
version: '3.1'

services:
  general-api:
    depends_on:
      - general-db
    ports:
      - 8082:8082

  general-db:
    environment:
      MYSQL_DATABASE: 'general'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    expose: # Exposes the port to other containers within same network
      - "3306"
    volumes:
      - general-db:/var/lib/mysql/data

volumes:
  general-db: