server:
  port: 8443
  ssl:
    enabled: false
    key-store: gateway-api/src/main/resources/ap-localhost.p12
    key-store-password: password
    key-store-type: PKCS12

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: file-delivery-api
#          uri: http://docker.no:8090/projects
#          predicates:
#            - Path=/projects/**

spring:
  application:
    name: gateway-api
