# docker-compose for local development
version: "3.1"

services:
    ###################
    # Web Application #
    ###################

    web-app:
        image: autopacker/webapp

    ####################
    # Backend Services #
    ####################

    # Authentication Server
    user-service:
        image: autopacker/userservice

    # General API
    general-api:
        image: autopacker/general-api

    # Server Manager
    server-manager:
        image: autopacker/servermanager

    # File Delivery API
    fdapi:
        image: autopacker/fsapi
        volumes:
            - fdapi_data:/usr/src/fdapi/data

    # Gateway API
    gateway:
        image: autopacker/gateway-api
        container_name: gateway
        ports:
            - 8000:8000
        depends_on:
            - config-srv
        networks:
            - backend-network
        volumes:
            - ${SSL_APP_LOCATION}:/home/dev/ssl/ap-stage.p12
            - gateway-mvn:/root/.m2/repository

    # Config Server
    config-srv:
        image: autopacker/config-srv
        volumes:
            - /home/dev/AutoPacker-Configuration:/etc/autopacker/config


    #############
    # Databases #
    #############

    fdapi-mongo:
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}

    mysql-backend:
        environment:
            MYSQL_DATABASE: ${MYSQLDB_DATABASE}
            MYSQL_USER: ${MYSQLDB_USERNAME}
            MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQLDB_RANDOM_ROOT_PASSWORD}

    ############
    # Keycloak #
    ############

    keycloak:
        image: autopacker/staging-keycloak
        ports:
            - 8443:8443
        volumes:
            - ${SSL_FULLCHAIN}:/etc/x509/https/tls.crt
            - ${SSL_PRIVKEY}:/etc/x509/https/tls.key

volumes:
    fdapi_data: