# docker-compose for local development
version: "3.1"

services:
  ###################
  # Web Application #
  ###################

  web-app:
    image: autopacker.azurecr.io/webapp

  ####################
  # Backend Services #
  ####################

  # API
  api:
    image: autopacker.azurecr.io/api
    volumes:
      - fdapi_data:/usr/src/fdapi/data

  # Gateway API
  gateway:
    image: autopacker/gateway-api
    volumes:
      - ${SSL_APP_LOCATION}:/home/dev/ssl/ap-stage.p12

  #############
  # Databases #
  #############

  fdapi-mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}

  mysql-backend:
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USERNAME}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQLDB_RANDOM_ROOT_PASSWORD}

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  ############
  # Keycloak #
  ############

  keycloak:
    image: autopacker/staging-keycloak
    ports:
      - 8443:8443
    volumes:
      - ${SSL_FULLCHAIN}:/etc/x509/https/tls.crt
      - ${SSL_PRIVKEY}:/etc/x509/https/tls.key
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  fdapi_data:
  ${SSL_FULLCHAIN}:
  ${SSL_PRIVKEY}:
  ${SSL_APP_LOCATION}:
