# docker-compose for local development
version: "3.1"

services:
  ###################
  # Web Application #
  ###################

  webapp:
    image: autopacker/local-webapp
    ports:
      - 80:80

  # web-app:
  #     container_name: web-app
  #     build:
  #         context: web-application
  #         dockerfile: dev.Dockerfile
  #     ports:
  #         - 3000:3000
  #     depends_on:
  #         # - user-service
  #         # - general-api
  #         # - server-manager
  #         - fdapi
  #     networks:
  #         - frontend-network
  #     volumes:
  #         # Mount the real source directories into the container - real-time changes will refresh the dev-build
  #         - ./web-application/src:/app/src
  #         - ./web-application/public:/app/public# docker-compose for local development

  ####################
  # Backend Services #
  ####################

  # API
  api:
    image: autopacker/local-api

  #############
  # Databases #
  #############

  fdapi-mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: "autopacker"
      MONGO_INITDB_ROOT_PASSWORD: "password"

  mysql-backend:
    environment:
      MYSQL_DATABASE: "autopacker"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  ############
  # Keycloak #
  ############

  keycloak:
    image: autopacker/local-keycloak
