# @formatter:off

# Environment-specific configuration. Replace all the ${}  with necessary values. Or configure the
# respective environment variables in your GIT pipeline.

###########
# General #
###########

server:
# The TCP port on which the REST API will be listening
  port: 8082

########################################
# KeyCloak authentication server setup #
########################################

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${AUTHORIZATION_SERVER_URL}
  ssl-required: ${SSL_REQUIRED} # default: external
  resource: ${SERVER_MANAGER_RESOURCE_ID}
  credentials:
    secret: ${SERVER_MANAGER_RESOURCE_SECRET}
  use-resource-role-mappings: ${USE_RESOURCE_ROLE_MAPPINGS} # default: true
  bearer-only: ${BEARER_ONLY} # default: true

########################
# Spring Configuration #
########################

spring:
  ############
  # Database #
  ############
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SERVER_MANAGER_DATABASE_HOST}:${SERVER_MANAGER_DATABASE_PORT}/${SERVER_MANAGER_DATABASE_NAME}
    username: ${SERVER_MANAGER_DATABASE_USERNAME}
    password: ${SERVER_MANAGER_DATABASE_PASSWORD}

#########################
# Application Constants #
#########################

api:
  root-url: http://127.0.0.1
  service-url: http://127.0.0.1:8082
  fdapi-url: http://127.0.0.1:8090

# @formatter:on