# @formatter:off

###########
# General #
###########

server:
  port: ${USER_SERVICE_SERVER_PORT}

############
# KeyCloak #
############

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${AUTHORIZATION_SERVER_URL}
  ssl-required: ${SSL_REQUIRED} # default: external
  resource: ${USER_SERVICE_RESOURCE_ID}
  credentials:
    secret: ${USER_SERVICE_RESOURCE_SECRET}
  use-resource-role-mappings: ${USE_RESOURCE_ROLE_MAPPINGS} # default: true
  bearer-only: ${BEARER_ONLY} # default: true

########################
# Spring Configuration #
########################

spring:
  ########
  # Mail #
  ########
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ############
  # Database #
  ############
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${USER_SERVICE_DATABASE_NAME}
    username: ${USER_SERVICE_DATABASE_USERNAME}
    password: ${USER_SERVICE_DATABASE_PASSWORD}

#########################
# Application Constants #
#########################

api:
  root-url: ${API_ROOT_URL}
  service-url: http://127.0.0.1:8081
  keycloak-url: http://127.0.0.1:8080
  client-username: ${API_CLIENT_USERNAME}
  client-password: ${API_CLIENT_PASSWORD}
  fdapi-url: http://127.0.0.1:8081

# Docker constants
docker:
  username: coreautopacker
  token: a4c0980e-19d4-4700-8821-899a9cce8c24
  repository: docker.io

######################
# Actuator & Logging #
######################

logging:
  file:
    path: ./src/main/resources/logs/
    max-history: 2
    max-size: 50MB

# @formatter:on