!!no.autopacker.webtests.TestConfig
# This first line tells that this config should be interpreted as a TestConfig object

# Save this file as application.yml in the resources folder, set the necessary values

# Credentials for AutoPacker admin-user
adminUsername: admin
adminPassword: admin

# Credentials for a regular-user without admin access
regularUsername: user
regularPassword: user


# Base URL of the web-app
url: http://localhost:3000

# Set this to true in environments where visual browser display is not necessary (docker)
headless: false