# Inspiration: https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
version: '3.3'
services:
  fdapi:
    container_name: fdapi
    image: autopacker/fsapi
    build:
      context: .
      cache_from:
        - fdapi:dev-0.1.0
    ports:
      - "8090:8090"
    depends_on:
      - "fdapi-mysql"
      - "fdapi-mongo"
    links:
      - fdapi-mysql:fdapi-mysql
    volumes:
      - ap-fs:/opt/fs/
      - mvn:/root/.m2/repository
      - /var/run/docker.sock:/var/run/docker.sock

  fdapi-mysql:
    container_name: fdapi-mysql
    image: mysql:8.0
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ap-db:/var/lib/mysql

  fdapi-mongo:
    container_name: fdapi-mongodb
    image: mongo:latest
    ports:
      - "27017"
    volumes:
      - ap-md:/var/lib/mongodb
volumes:
  ap-fs:
  ap-db:
  ap-md:
  mvn: