# docker-compose for local development
version: '3.1'

services:
  userservice:
    depends_on:
      - user-db
    ports:
      - 8080:8080

  user-db:
    environment:
      MYSQL_DATABASE: 'auth'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    expose: # Exposes the port to other containers within same network
      - "3306"
    volumes:
      - user-db:/var/lib/mysql/data

volumes:
  user-db: