# This workflow should be executed when a merge request to
# develop or master including changes to file delivery api is accepted
name: General API Build

on:
  push:
    branches:
      - master
      - develop
    paths:
      - general-api/**

jobs:

  # Build and publish docker image for local development
  build_local-general-service:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push the general service docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: autopacker/local-general-api
        tags: latest
        path: ./general-api
  
  # Build and publish docker image for the general service
  build_general-service:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: change config server bootstrap value
      run: sed -i 's/localhost/stage.autopacker.no/' ./general-api/src/main/resources/bootstrap.yml
      
    - name: Build and push the general service docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: autopacker/general-api
        tags: latest
        path: ./general-api
