name: API Build

on:
  push:
    branches:
      - develop
    paths:
      - api/**

jobs:
  # Build and publish a local docker image for development
  build_local-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push the local api docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: autopacker/local-api
          tags: latest
          path: ./api
