# This workflow should be executed when a merge request to
# develop or master including changes to file delivery api is accepted
name: File Delivery Build

on:
  push:
    branches:
      - master
      - develop
    paths:
      - file-delivery-api/**

jobs:
  
  # Build and publish docker image for the file service
  build_file-delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: change config server bootstrap value
      run: sed -i 's/localhost/stage.autopacker.no/' ./file-delivery-api/src/main/resources/bootstrap.yml
      
    - name: Build and push the file service docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: autopacker/fsapi
        tags: latest
        path: ./file-delivery-api