# Manual action for deploying the latest changes for General API
# in [master] branch to the staging server
name: Deploy General API

on:
  workflow_run:
    workflows:
      - General API Build
  types:
    - completed

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        password: ${{ secrets.STAGING_PASSWORD }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          cd ./AutoPacker
          docker image pull autopacker/general-api
          docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d --force-recreate general-api