name: Deploy Web Application

on:
  workflow_run:
    workflows:
      - Web Application Build
    types:
      - completed

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Login to azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          docker image pull autopacker.azurecr.io/webapp

    - name: Deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_PASSWORD }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          cd ./AutoPacker
          docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d --force-recreate web-app