# Manual action for deploying the latest changes for Server Manager
# in [master] branch to the staging server
name: Deploy Server Manager

on:
  workflow_run:
    workflows:
      - Server Manager Build
    types:
      - completed

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_PASSWORD }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          cd ./AutoPacker
          docker image pull autopacker/servermanager
          docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d --force-recreate server-manager
