# Manual action for deploying the latest changes in [develop] branch to the staging server
name: Deploy Repo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: "Deploy the latest changes in branch [develop]"
        default: "latest"
        required: true

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PASSWORD }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd ./AutoPacker
            git pull
