name: Deploy User Service

on:
  workflow_run:
    workflows:
      - User Service Build
    types:
      - completed

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PASSWORD }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd ./AutoPacker
            git pull
            docker image build -t autopacker/api .
            docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d --force-recreate api
